### PR TITLE
Fixed minor bug in 00_Setup.md instructions

### PR DESCRIPTION
**Pull request by fluidai**

### CODE REVIEW

**Comment by fluidai** [comment]
@googlebot I signed it!

**Comment by danisla** [comment]
@fluidai can you confirm that the author email in the commit log matches the one you signed the CLA with? I think that is the issue with the bot.

**Comment by fluidai** [comment]
@googlebot I signed it!

**Comment by fluidai** [comment]
> @fluidai can you confirm that the author email in the commit log matches the one you signed the CLA with? I think that is the issue with the bot.

Yup, i fixed it, thanks

**Comment by danisla** [comment]
Great, LGTM. Thanks!

**Pull request merged**
